# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run perflogs on MongoDB testing cluster

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "*/20 * * * *"
      
jobs:
  runlog:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true
    - run: npm install
    - name: Start run
      run: npm start
      env: 
        MONGO_URL: ${{secrets.MONGO_URL}}
